version: '3.9'
services:
  database:
      image: postgres
      volumes:
        - data:/data/db
      env_file:
        - .env
      ports:
        - 6000:5432
      restart: on-failure
      networks:
        - databaseNetwork

  app:
    build: 
      context: .
      network: host
    ports:
      - "80:80"
    restart: on-failure
    networks:
      - databaseNetwork

  etl:
    build: 
      context: etl/
      network: host
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - databaseNetwork

networks:
  databaseNetwork:
    driver: bridge
    name: databaseNetwork

volumes:
  data: